# Generated by Django 2.2.7 on 2021-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parachapp', '0002_auto_20210622_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadvancedprofile',
            name='payment_status',
            field=models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Not Fully Paid', 'Not Fully Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=16),
        ),
    ]
